version: "2"
services:
  consul:
    image: consul:0.7.0
    container_name: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "agent -server -client 0.0.0.0 -bootstrap-expect 1 -ui-dir /ui"

  clever_app:
    build:
      context: .
      dockerfile: Dockerfile.clever
    ports:
      - "9010-9020:9010-9020"
